### ISSUE TITLE
Minify, combine and cache partials

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#1]
I love Radian, it seems to very closely replicate what I have been trying to do with Angular and Yeoman myself, except Radian is a lot cleaner and more clearly thought-out.

One thing I feel is missing from Radian is minification/combining of partials for the production version of the app. Perhaps take a look at [grunt-angular-templates](https://github.com/ericclemmons/grunt-angular-templates). I tend to use a lot of small partials and making multiple requests for a few small partials makes app significantly slower on production. You can also transparently fallback to using `.html` files (perhaps for the development version) and continue to use the same path.

**Comment by ahmednuaman** [comment]
Yes, this is something I've been thinking about, I'll have a look now.
