### ISSUE TITLE
Support multiple modules?

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#17]
Having more than one module has become more difficult because the helper base classes are coupled to the module that is defined in the config file.

I'm not sure how I feel about this, I have only ever used one module in the past so I don't think it will effect me but I think it's worth raising the issue because 'scalable' applications could legitimately be broken down into multiple modules.

If this is considered an issue then there are two potential solutions that I can think of.
1. Require (or make optional) the module name in the `@register` method.
2. Use a generator that creates module specific base classes. i.e. `yo radian:module 'module name'` creates a ModuleNameCtrl/ModuleNameService/etc base class.

Again, I'm not sure that this is an issue that needs to be fixed but I think it's worth considering.

**Comment by ahmednuaman** [comment]
Indeed, I think I see an 'app' as a 'module', so a new module would be a new app, per sa. But it is a valid point. I'll have a think.

**Comment by ahmednuaman** [comment]
So I discussed this with my colleagues and an interesting point was made about bower: if you're on a project and you're writing multiple modules then it's _better_ to separate them and require them via bower. This way the code is cleaner and focused.
