### ISSUE TITLE
You are leaking your key.

### ISSUE THREAD

**Issue by GUIpsp** [ahmednuaman/radian#24]
```
Using the selenium server at ahmednuaman-radian:06dd4e07-0f52-4fdf-be5e-389f2117bbf5@localhost:4445
```

**Comment by ahmednuaman** [comment]
I know, but this is an open source project and that account is only linked to this project, so it doesn't really matter. I mean the tests and their results are going to be published anyway, so I'm cool with it.

**Comment by ahmednuaman** [comment]
Actually this is a valid point, even if it is open source. I'll look at hiding the protractor output.

**Comment by ahmednuaman** [comment]
I'll set `stdout` to `false` if this is run on Travis. https://github.com/jharding/grunt-exec/blob/master/README.md

**Comment by ahmednuaman** [comment]
Updated, also the key has been reset: ea673ed0d0fad415784ee33ab0414ffe9ff348ac

**Comment by ahmednuaman** [comment]
Also: https://travis-ci.org/ahmednuaman/radian/jobs/16254122#L7479
