### ISSUE TITLE
Reference to source maps are incorrect

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#25]
Using Chrome 31.0.1650.63, a screenshot explains this best.

![screen shot 2014-01-02 at 15 46 08](https://f.cloud.github.com/assets/26971/1833194/3d17c52c-73c5-11e3-9003-f75052c88b58.png)

**Comment by ahmednuaman** [comment]
Yep I see this too, I think this should probably be moved to https://github.com/gruntjs/grunt-contrib-coffee/issues
