### ISSUE TITLE
Crawler overwrites main `index.html` file

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#3]
When I run `grunt build` everything runs file until it gets to the crawler and outputs "`Indexed http://localhost:8000/ and saved to build/index.html`". Basically the crawled `index.html` replaces the original `index.html`.

This means that I can not access the built JS version of the site, I am presuming that this is not the expected behaviour.

**Comment by ahmednuaman** [comment]
I'll look into it now.

**Comment by ahmednuaman** [comment]
So yes this is expected behaviour. First we copy the `index.html` to the `build/` folder and then if crawling is enabled it needs to overwrite it with the generated `index.html` for SEO reasons. Since the Angular `ng-*` attributes are all there the app functions just fine. :)

**Comment by davej** [comment]
Ah ok, that's quite smart. I guess this means that you can't bind using {{ curly }} inline variables?

i.e. `<div>{{ variable }}</div>`

**Comment by ahmednuaman** [comment]
You can, in fact this crawler takes a snapshot of the site for SEO purposes. I prefer to use `ng-bind` but by all means you can use `{{ foo }}`, check out https://github.com/ahmednuaman/radian/blob/master/assets/partial/directive/menu-component-partial.jade

**Comment by davej** [comment]
The SEO version will work fine with `{{ foo }}` but when I load up the file with JS enabled then `foo` wont be bound.

i.e. `<title>{{ pageTitle }}</title>` becomes `<title class="ng-binding">Radian ~ A scalable AngularJS framework ~ What is Radian?</title>` in index.html. So If I change pageTitle using angular in the JS version of the site then it won't update the text in the `title` tag because Angular isn't aware of the binding.

Anyway, I normally use `ng-bind` anyway but it's good to be aware of the gotcha.

**Comment by ahmednuaman** [comment]
Ah yes correct but that'll only happen in non-partialed views, eg (as you rightly said) the `<title>` tag, hence why I used an `ng-bind`. I don't think it'll be a problem as you should really use a partial if you're gonna display some data and it'll keep the `index.jade` clean.
