### ISSUE TITLE
 The package karma does not satisfy its siblings' peerDependencies requirements!

### ISSUE THREAD

**Issue by jcarras** [ahmednuaman/radian#35]
NPM install not finishing and showing following error. I have karma 0.10.9 installed globally.

npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.2 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.2.1 wants karma@>=0.9
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.2.1 wants karma@>=0.11.14
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.2 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-coverage@0.2.0 wants karma@>=0.9

npm ERR! System Darwin 13.1.0
npm ERR! command "node" "/usr/local/bin/npm" "install" "karma"
npm ERR! cwd /Users/jca27/Dev/sq-web-v2
npm ERR! node -v v0.10.24
npm ERR! npm -v 1.3.21
npm ERR! code EPEERINVALID

**Comment by jcarras** [comment]
FYI: Globally Karma 0.10.9 is installed.

**Comment by ahmednuaman** [comment]
I've updated master (1add5d526f8facc0cdeb148c1fba837c36fc72a4) so try cloning it and trying it out.

**Comment by ahmednuaman** [comment]
Is this resolved now?

**Comment by jcarras** [comment]
upgrading yeoman did not seem to work.

## 

Joel Carras
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ahmednuaman** [comment]
Sorry I meant when you upgraded Radian, did it all work fine?

**Comment by jcarras** [comment]
When I initialised a yeoman project, then cloned radian from master into the same directory everything was golden.

## 

Joel Carras
Sent with Sparrow (http://www.sparrowmailapp.com/?sig)

**Comment by ahmednuaman** [comment]
Ok cool.
