### ISSUE TITLE
Issues with dependencies when running: yo radian

### ISSUE THREAD

**Issue by jeffstahlin** [ahmednuaman/radian#36]
I am on OSX Mavericks 10.9.3 and have followed the instructions on your homepage for installing Radian as well as Yeoman. All is fine here.

Now when I want to create an app with the "yo radian" command I get the following two errors:

```
./util/has_cairo_freetype.sh: line 4: pkg-config: command not found
gyp: Call to './util/has_cairo_freetype.sh' returned exit status 0. while trying to load binding.gyp
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:340:16)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:797:12)
gyp ERR! System Darwin 13.2.0
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /Users/xxx/Documents/dev/radian/node_modules/grunt-spritesmith/node_modules/spritesmith/node_modules/canvassmith/node_modules/canvas
gyp ERR! node -v v0.10.26
gyp ERR! node-gyp -v v0.13.0
gyp ERR! not ok
```

and at the end I get: 

```
npm ERR! peerinvalid The package karma does not satisfy its siblings' peerDependencies requirements!
npm ERR! peerinvalid Peer karma-chrome-launcher@0.1.2 wants karma@>=0.9.3
npm ERR! peerinvalid Peer karma-firefox-launcher@0.1.3 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-html2js-preprocessor@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-jasmine@0.1.5 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-requirejs@0.2.1 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-script-launcher@0.1.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-junit-reporter@0.2.1 wants karma@>=0.9
npm ERR! peerinvalid Peer grunt-karma@0.6.2 wants karma@~0.10.0
npm ERR! peerinvalid Peer karma-coffee-preprocessor@0.2.1 wants karma@>=0.11.14
npm ERR! peerinvalid Peer karma-coverage@0.2.0 wants karma@>=0.9
npm ERR! peerinvalid Peer karma-phantomjs-launcher@0.1.2 wants karma@>=0.9

npm ERR! System Darwin 13.2.0
npm ERR! command "node" "/usr/local/bin/npm" "install"
npm ERR! cwd /Users/xxx/Documents/dev/radian
npm ERR! node -v v0.10.26
npm ERR! npm -v 1.4.10
npm ERR! code EPEERINVALID
```

Have you got any advice on how to fix these issues or references I could read through that would help me solve the problem? I have looked around on Google but haven't found any solutions that have solved anything for me. Such solutions included updating Karma to the latest version but that also ups the version of grunt-karma that is needed and all other dependencies listed didn't seem to get solved by this. 

Any help at all would be great as I am really anxious to give Radian a try.

**Comment by ahmednuaman** [comment]
Thanks for wanting to give Radian a try. This issue is pretty much the same as #35, can you try cloning master and then running the `yo` generator on top? I'm about to do a new release in the next couple of weeks but if you can't wait til then this'll work.

**Comment by jeffstahlin** [comment]
Wow what a fast reply. Ok I will give that a go. 

Thanks for your help. Will post here to let you know the outcome.

**Comment by ahmednuaman** [comment]
:+1:

**Comment by jeffstahlin** [comment]
I cloned the folder, navigated to it in terminal and ran "yo radian" again. This lead to many requests to overwrite existing files, which I hit yes for each one. After that it goes through the installation as usual and the same errors come up as before.

Have I done something wrong here?

**Comment by ahmednuaman** [comment]
Ok, try this:
1. Creating a new, clean project using `yo radian`
2. Clone `master` into another folder
3. Copy, from `master` the following files into the same location
   - `package.json`
   - `bower.json`
   - `server.coffee`
   - `crawler.coffee`
   - `test/unit/karma.conf.coffee` (or js)
4. Run `npm install`

The reason you're getting this error is because the version of Karma you have installed globally isn't the same as what's required by Radian, eg run `karma -v` and it probably won't be `0.10.x`

**Comment by jeffstahlin** [comment]
Thanks ahmednuaman, that's helped a lot. The 'gyp' error is still there but doesn't seem to be interfering with anything for now.  And indeed, it seemed I didn't even have karma installed...I installed it on another machine late last night, not the one I am on now (clearly not sleeping enough lately lol). Also I am fairly new to using Bower, Grunt and Yeoman so thank you very much for clearing up these issues. 

At the risk on being a pain, I still have one last issue now when running 'grunt'. I get the following error:

```
Running "express:all" (express) task
Starting background Express server
You are using cmd: coffee
coffee does not allow a restart of the server
use opts: ["path/to/your/coffee"] instead
Listening on port: 8000

Running "watch" task
Waiting...
```

On waiting it just hangs there. In case it helps to know, due to the error reported, I am using js rather than coffee in this app.

Again thank you for your help.

**Comment by jeffstahlin** [comment]
Ok I managed to fix the issue that express server displayed. 

Still goes through to Waiting.... and hangs there. Is this normal? Do I need to perform any other action from here?

**Comment by jeffstahlin** [comment]
Right, went to localhost:8000 in the browser and I see the Radian homepage (I installed the demo files). So I assume this is all working now.

Thank you so much for your help, I really appreciate it. 

Woohoo, am excited to give Radian a go now :-)

**Comment by ahmednuaman** [comment]
:+1:
