### ISSUE TITLE
Live Reload for SASS?

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#4]
I think I understand why you haven't included live reload. It can be very frustrating when you save a file without thinking and the app reloads causing the application state to be lost.

It is super useful for SASS though because it can update CSS without refreshing the browser and keeping the browser state in tact. What do you think about the idea of including Live Reload for CSS files only?

**Comment by ahmednuaman** [comment]
Care to elaborate?

**Comment by ahmednuaman** [comment]
`livereload: true` is currently there, how do I stop the browser refreshing? https://github.com/ahmednuaman/radian/blob/master/grunt/contrib-watch.coffee#L23

**Comment by davej** [comment]
Yes but I don't see where you start up an instance of the live reload server? Or where you inject the instance into the index.html file?

The browser shouldn't refresh if you look for changes in the compiled `.css` files instead of `.sass` files.

**Comment by ahmednuaman** [comment]
So the livereload server is started by https://github.com/gruntjs/grunt-contrib-watch#optionslivereload, that's part of the `grunt [default]` task on Radian. As for injecting the HTML, I just use the browser extensions and they add the HTML. This way people have a choice as to how they use (or not use) livereload.

**Comment by davej** [comment]
Ah cool, I see now, that makes sense.

I've added a pull request to fix the CSS reloading without a hard-refresh
