### ISSUE TITLE
Broken when you choose to generate an app without example site code

### ISSUE THREAD

**Issue by davej** [ahmednuaman/radian#6]
I'm sure you're aware of this but it doesn't seem to be mentioned on the site.

Some but probably not all of the things that are broken:
- `@import 'icon/*.png'` the folder and `png` files don't exist, causes compass:dev to abort (`styles.sass`)
- `@import 'partial/mixins'` etc.., none of the partials exist, causes compass:dev to abort (`_partials.sass`)
- `app-controller.coffee` has references to `header-controller`, `footer-controller` and `page-title-factory`, all of which don't exist. This creates the error `Unknown provider: pageTitleFactoryProvider <- pageTitleFactory`
- `routes.coffee` has references to `error-controller` and `home-controller` which don't exist

Also when files aren't found they don't raise 404's they just return the index.html file instead. Perhaps if the path has a .js/.css/.jpg/.png/.gif extension then the server should return a 404 instead of the index.html file

**Comment by davej** [comment]
Oops this issue should probably be in the `generator-radian` repo.

**Comment by ahmednuaman** [comment]
Yep, it's all a bit busted at the moment. I've created an issue to deal with code duplication and what not: https://github.com/ahmednuaman/generator-radian/issues/1

I'll sort this today.

**Comment by ahmednuaman** [comment]
Deploying a new version of the generator now. All is well.
